### ISSUE TITLE
Refusing to install clappr-video360 as a dependency of itself

### ISSUE THREAD

**Issue by amoghkashyap** [thiagopnts/clappr-video360#12]
npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "clappr" "clappr-video360"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install clappr-video360 as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!   Desktop/video_player/clappr-video360/npm-debug.log

using npm version 3.10.10
OS: linux 16.04

**Comment by thiagopnts** [comment]
weird, this happens when you try to `npm install clappr-video360`?

**Comment by amoghkashyap** [comment]
yes, could you kindly check?

**Comment by thiagopnts** [comment]
I couldn't reproduce on macOS with npm 3.10.10 and 4.2.0. Is it inside a project with a package.json that you can share?

**Comment by amoghkashyap** [comment]
yes. 

{
  "name": "clappr-video360",
  "version": "0.0.3",
  "description": "360 video plugin for Clappr",
  "main": "dist/clappr-video360.min.js",
  "dependencies": {
    "kaleidoscopejs": "^1.0.13",
    "clappr": "0.2.57"
  },
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015-rollup": "^3.0.0",
    "rollup": "^0.33.0",
    "rollup-plugin-babel": "^2.6.1",
    "rollup-plugin-commonjs": "^3.0.2",
    "rollup-plugin-node-resolve": "^1.7.1",
    "rollup-plugin-strip": "^1.1.1",
    "rollup-plugin-uglify": "^1.0.1",
    "sinon": "^1.17.3",
    "uglify-js": "^2.6.4",
    "webpack": "^1.14.0"
  },
  "scripts": {
    "build": "node_modules/.bin/rollup -c",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/thiagopnts/clappr-video360.git"
  },
  "keywords": [
    "clappr",
    "360",
    "video"
  ],
  "author": "Thiago Pontes <github@thiago.me>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/thiagopnts/clappr-video360/issues"
  },
  "homepage": "https://github.com/thiagopnts/clappr-video360#readme"
}

**Comment by thiagopnts** [comment]
oh I see, that's why you're using this repo's package.json. you should create a new directory for your project, run `npm init` and then you can `npm install clappr-video360`

if you want to run the index.html that is inside of this repo, you just have to run `npm install && npm run build`, then serve the `index.html` from some local web server, like `python -m SimpleHTTPServer`.
Let me know if you have any other problems
