### ISSUE TITLE
Player size on mobile is too cropped

### ISSUE THREAD

**Issue by samcarmex** [thiagopnts/clappr-video360#15]
I've noticed that the way the 360 video is cropped/framed on mobile is distorted and incorrect when comparing to desktop crop/zoom. See below screenshots of same video on both desktop and mobile layout:

[Mobile: https://imgur.com/a/YvQLI](https://imgur.com/a/YvQLl)
[Desktop: https://imgur.com/25YMhH8](https://imgur.com/25YMhH8)

What could be causing this and how do we correct the mobile view to reflect the desktop view?

**Comment by Zvih** [comment]
Also this issue can be reproduced on your demo page
http://thiago.me/clappr-360/

One important thing, player should be initialized on narrow mobile layout

Player starts on wide screen
![image](https://user-images.githubusercontent.com/12168912/38178794-eac04fae-3622-11e8-8349-560f3b5f0f01.png)

After screen resize, ok
![image](https://user-images.githubusercontent.com/12168912/38178807-392925f8-3623-11e8-9659-37efbec8d840.png)

Player start on narrow screen, failed
![image](https://user-images.githubusercontent.com/12168912/38178796-f5ad097a-3622-11e8-98db-c781bd857cc6.png)

**Comment by samcarmex** [comment]
Just updated to latest release and problem is now resolved - will mark as closed. Cheers!
