### ISSUE TITLE
360 video is shaking on android

### ISSUE THREAD

**Issue by mawais78** [thiagopnts/clappr-video360#17]
I'm trying to play http://thiago.me/clappr-360/ on my laptop this is working as expected. But I'm trying to open this video on my galaxy S8+ but the video is shaking even when I put my mobile on floor or static place. I also tried this on another mobile oneplus 5t but the issue is same. Anyone facing this issue or have nay solution for this problem.

I'm trying to open this video on chrome browser version 70.0.3538.110 on mobile.

**Comment by thiagopnts** [comment]
I updated the lib and released v0.0.6, it should be fixed now!
