### ISSUE TITLE
fullscreen issue for 360 plugin

### ISSUE THREAD

**Issue by Vaish00** [thiagopnts/clappr-video360#19]
Hello Thiago,
I am working on 360pulgin, so when i click on fullscreen it goes to fullscreen mode but the video content remains the same i.e the video inside it does not cover the video

**Comment by thiagopnts** [comment]
Weird, it works for me here: http://thiago.me/clappr-360/
Which browser are you using?

**Comment by Vaish00** [comment]
Hey Thiago, 
How you doing?
I am using chrome

**Comment by thiagopnts** [comment]
fullscreen is working for me on chrome and iPadOS. Closing this for now, let me know if you have any issues
