### ISSUE TITLE
Plugin for Grind Player

### ISSUE THREAD

**Issue by seamug** [thiagopnts/clappr-video360#2]
Any chance of developing one for Grind?

Thanks

**Comment by thiagopnts** [comment]
Probably not. I just did it for Clappr because I'm very familiar with how it works. But I think you can easily adapt the code to run outside of it, this file basically does everything: https://github.com/thiagopnts/video-360/blob/master/viewer.js

**Comment by thiagopnts** [comment]
I think now it would be easy to implement this for any player by using this https://github.com/thiagopnts/kaleidoscope
