### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by DanieleSuppo73** [thiagopnts/clappr-video360#23]
Hi, this plugin does not work on Safari iOS 10

**Comment by thiagopnts** [comment]
Does any errors show up?

**Comment by DanieleSuppo73** [comment]
I don't know, unfortunately I can't make work Chrome dev tools from my PC to iPhone

**Comment by DanieleSuppo73** [comment]
I can confirm you that there are no errors in console.
P.s. the audio is working, the video is black

**Comment by DanieleSuppo73** [comment]
Hi, any news?
It does not work or any iOS device.
Many thanks for your work!

**Comment by thiagopnts** [comment]
Sorry for taking forever to look into this, its fixed on v0.0.7 that I just published
