### ISSUE TITLE
Adding touchevent support

### ISSUE THREAD

**Issue by reevolutn** [thiagopnts/clappr-video360#3]
I've modified your js file as follows and tested on Android and iPad. No support for iPhone as it forces the video to go fullscreen.

<pre>
this.renderer.domElement.addEventListener("touchend", this.onMouseUp.bind(this), !1), 
this.renderer.domElement.addEventListener("touchmove", this.onTouchMove.bind(this), !1),
this.renderer.domElement.addEventListener("touchstart", this.onTouchDown.bind(this), !1),
</pre>

I left touchend bound to onMouseUp as it doesn't need to access the event data.

I also added the following:

<pre>
}, {
    key: "onTouchMove",
    value: function(e) {
        this.isUserInteracting && (this.lon = .2 * (this.onPointerDownPointerX - e.changedTouches[0].pageX) + this.onPointerDownLon, this.lat = .2 * (e.changedTouches[0].pageY - this.onPointerDownPointerY) + this.onPointerDownLat)
    }
}, {
    key: "onTouchDown",
    value: function(e) {
        e.preventDefault(), this.isUserInteracting = !0, this.onPointerDownPointerX = e.changedTouches[0].pageX, this.onPointerDownPointerY = e.changedTouches[0].pageY, this.onPointerDownLon = this.lon, this.onPointerDownLat = this.lat, this.renderer.domElement.classList.add("dragging")
    }
</pre>

**Comment by thiagopnts** [comment]
Nice, did it worked fine? It would be nice if you could send a PR with those changes

**Comment by thiagopnts** [comment]
touch support add in the latest version
