### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by FernandoJBCosta** [thiagopnts/clappr-video360#7]
Hello Thiago nice work here, I'm testing your 360Plugin and I see that is not dynamic responsive if this is the correct name name :), when you resize the browser window the page stays with the same size and, is there any way I cold correct that?
Another thing is I am trying to play inline on iOS but without success can you tell me how I can do this?
you can check the demo here: http://cdn.360play.pt

Best regards.
Fernando Jorge

**Comment by thiagopnts** [comment]
Hey, yes it's not responsive. I'll check if clappr has any resize events or bind to the window to resize the canvas when needed. About the iOS support I have plans to add basic support for iOS 10 soon

**Comment by FernandoJBCosta** [comment]
Hello Thiago any news about the iOS support?

Best regards

**Comment by thiagopnts** [comment]
I'm closing this since the plugin now works on iOS and is set to follow any resizes in the player, so responsiveness can be implemented easily by the dev embedding
