### ISSUE TITLE
not setting width and height？

### ISSUE THREAD

**Issue by smallSquirrel** [thiagopnts/clappr-video360#8]
Clappr set the width and height, the panoramic video playback, the screen is black, but have voice; I tried not Panorama plug-in, the video can be watched, do panoramic spherical calculation is related to the width and height? If not, how do I do it; thank you for any help；

Here is my pseudocode : 
    ` var p = new Clappr.Player({
        source: 'http://example.m3u8',
        plugins: {
            container: [Video360]
        },
        parentId: '#vr-player',
        autoPlay:true,
        width:"1000px",
        height:"500px"
    });
    p.getPlugin('click_to_pause').disable();`

system：Windows 8.1
browser：chrome 54
clappr:  0.2.59

**Comment by FernandoJBCosta** [comment]
Hello, try this:

var p = new Clappr.Player({source: "http://example.m3u8", watermark: "logo.png", position: "top-right", chromeless: false, autoPlay: false, width: window.innerWidth, height: window.innerHeight, plugins: {container: [Video360]}, parentId: "#vr-player"});
		p.getPlugin('click_to_pause').disable();

		window.addEventListener("resize", function() {
			p.resize({width: window.innerWidth, height:window.innerHeight});
		});
Best regards
PS: you can put the width and height values in your <div>

**Comment by thiagopnts** [comment]
yes, the width and height parameters must be a number
