### ISSUE TITLE
how to update latest version of kaleidoscope

### ISSUE THREAD

**Issue by alyen028** [thiagopnts/clappr-video360#9]
Hi thiagopnts:
     How can i update kaleidoscopejs? thanks!

**Comment by thiagopnts** [comment]
Hey, you can get the latest version from npm, or checking out the latest tag

**Comment by thiagopnts** [comment]
published as 0.0.3

**Comment by alyen028** [comment]
Hi Thiago:
    npm version: windows - 3.8.9; linux - 3.8.3。
    now, update clappr-video360 to latest version@0.0.3, it's Ok！
    thanks very much！






At 2016-12-31 02:52:56, "Thiago Pontes" <notifications@github.com> wrote:


published as 0.0.3
